version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: khan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newtodo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-container
    environment:
      DATABASE_URL: "postgresql+asyncpg://khan:password@db/newtodo"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    # entrypoint: ["/app/entrypoint.sh"]

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
